trendmicro/tlsh

- py_ext/tlshmodule.cpp
A typo was preventing hash_py function from accepting strings as its input. I changed the input format. It now works under Python 3.4.2 and Python 2.7.8. However, there might be a need for someone to test under 2.7.8 more extensively as I primarily work with 3.x .
Thank you.
> Fixed a typo in py_ext/tlshmodule.cpp

- make.sh
In the shebang we just use "sh", so we must not use any Bash specific
constructs.
> Remove a Bash-ism from make.sh

- Testing/python_test.sh
this resolves the issue that the library needs to be installed
into the system before the tests can work correctly.
Also it is possible to pass the python executable as the first
parameter, allowing to test both, python2 and python3
external CARCH environment var allowes to either override the arch
(on cross-platform packaging of i686 packages build on x64) or get
the default architecture via uname -m
> using PYTHONPATH to run tests against local library

- py_ext/tlshmodule.cpp
this fixes python3 and ensures for both, python2 and python3 that
the passed argument is a string.
this fixes #14
> convert arg to bytes object before passing to PyBytes_AsStringAndSize

- src/CMakeLists.txt
We add CMake install directives in order to see the library files installed in
the expected multiarch compatible locations.
This is useful for packaging tlsh and distribute the shared library along with the header etc.
> adding make target to install the library in expected directories

- test/tlsh_unittest.cpp
trendLSH_ut allocates max_files*sizeof(struct FileName) times max_files memory to hold the filenames, we only need max_files*sizeof(struct FileName)
> Fixed memory allocation bug in tlsh_unittest and add NULL check (Large Dir Crash)

- README.md
As @armijnhemel said in https://github.com/trendmicro/tlsh/issues/32, the referenced Java port of triplecheck returns HTTP 404. 
Updating this link to https://github.com/idealista/tlsh
> updating unavailable Java port link to idealista/tlsh

- java/.classpath
- java/.project
- java/.settings/org.eclipse.jdt.core.prefs
- java/README.md
- java/build.gradle
- java/settings.gradle
- java/src/test/java/com/trendmicro/tlsh/ExampleDataUtilities.java
JAR files are much more likely to be used if they're available through common distribution platforms so I've set up an account on bintray.com and modified the build script to make upload painless.
Major changes:
* switch to source level 1.7 from 1.8 to make the compiled code usable by those stuck on older versions of Java
* modify build.gradle to use the bintray plugin so that uploads can be automated
* Update README to point to current bintray distribution of the library
> Publish compiled JAR file on bintray.com

- py_ext/tlshmodule.cpp
I thought my *machine* did not have enough entropy until I looked at the
code.
(I've copied this text from another extension)
Via development on https://diffoscope.org
> Please clarify "lack of entropy" error message.

- js_ext/tlsh.js
When running this in the latest chrome I got an undefined error for tmpArray. Defining it with let resolves the error.
> Fix tmpArray is undefined

- java/.classpath
- java/.project
- java/.settings/org.eclipse.buildship.core.prefs
- java/.settings/org.eclipse.jdt.core.prefs
- java/README.md
- java/build.gradle
- java/gradle/wrapper/gradle-wrapper.properties
- java/settings.gradle
- java/src/main/java/com/trendmicro/tlsh/Tlsh.java
- java/src/main/java/com/trendmicro/tlsh/TlshCreator.java
- java/src/main/java/com/trendmicro/tlsh/TlshUtil.java
- java/src/main/java/com/trendmicro/tlsh/VersionOption.java
- java/src/main/resources/README.md
- java/src/test/java/com/trendmicro/tlsh/TlshTest.java
* Update TLSH Java implementation to understand new TLSH version data
* Partial fix for issue #84 to allow TLSH on files up to 4GiB
* Fix unit tests to work with new test data files
* Remove bintray hosting as it is being shut down
> Java fix for issue #99

- make.sh
- src/CMakeLists.txt
Proposed fix for the issue #91 
If we do not want to remove the `make install` target for compatibility reason, we might as well own it and make it work properly.
I also added a way to build the shared lib version without having to modify cmake files as I feel the two modifications work in tandem
closes #91
> Fix the make install target by adding the `version.h` in the installed files

- include/tlsh.h
- include/tlsh_impl.h
- test/tlsh_unittest.cpp
Just a few fixes. I converted #if defined WINDOWS || defined MINGW
to #if defined(WIN32) || defined(_WIN32) || defined(__WIN32) && !defined(CYGWIN)
> Pull request #66

- py_ext/tlshmodule.cpp
Providing a fix to the issue #125 
Modified the tlshmodule to fix the memory leak.
> [Fix] Memory Leak in py-tlsh

- CMakeLists.txt
- Change_History.md
- README.md
- include/tlsh_win_version.h
18/09/2024
document what has changed since **4.11.2** on 23/10/2021
Merge pull request #137 - this fixed a memory leak in py-tlsh
Merge pull request #134 - this improved the ifdef WINDOWS to be more portable
> **4.12.0**

- src/tlsh_impl.cpp
This is a continuation after the commit 755f31e75a59 ("3.12.0") which removed the dependency to the float log.
Once we find quartile values in TLSH, we perform a float division to get q1/q3 and q2/q3 in percentage (and taken the mod 16) but lacks portability (and has a bug which the committer explains later).
Note: `q1 <= q2 <= q3`.
If we have a 32-bit divider, a 64-bit / 32-bit division is not that a big cost (it's theoretically one instruction in x86 because the `DIV` instruction performs a 64-bit / 32-bit division, not 32-bit / 32-bit).
It also fixes the problem of arithmetic overflow calculating unsigned 32-bit `(q1*100)` and `(q2*100)` (if they overflow, the ratio will be an unexpected value).
Note:
`(q1*100)` and `(q2*100)` in `u32` is clearly a bug (in a normal sense) but I'm not …
> Bug Fix+Portability: Improve portability by integral division

- CMakeLists.txt
- include/tlsh.h
This commit sets default options only when no related options are specified.
With this, full hash (256 bucket variant) will compile just by `-DTLSH_BUCKETS_256=1`.
Just fixing CMakeLists.txt caused an error due to a failure to track with other changes on the version 4.0.0 on min hash (48 buckets variant) so this commit also fixes this issue.
> Build: Define default options only on "default"

- py_ext/tlshmodule.cpp
This change allows building the Python extension for Python 3.12 with musl.
Patch first introduced in Gentoo: https://github.com/gentoo/gentoo/pull/36321
> py_ext: use PyVarObject_HEAD instead of PyObject_HEAD_INIT

- test/tlsh_unittest.cpp
@jonjoliver can you review it please?
Although `sprintf()` is considered insecure, in this case it's harmless as the string copied to `nullstr` is fixed. However, because this function is deprecated, the compiler emits a warning. This patch removes the function call as it's not really needed in this case.
> Remove call to sprintf() to avoid warnings

- CMakeLists.txt
- Change_History.md
- README.md
- include/tlsh_win_version.h
<PRE>
08/10/2024
Merge pull request #146 - Remove call to sprintf() to avoid warnings
Merge pull request #141 - py_ext: use PyVarObject_HEAD instead of PyObject_HEAD_INIT
Merge pull request #138 - Build: Define default options only on "default"
Merge pull request #136 - Bug Fix+Portability: Improve portability by integral division
</PRE>
> README.md / Change_History.md / version numbers for **4.12.1**
